version: '3.3'
services:
    maccms:
        build:
            context: ./maccms
        container_name: maccms
        restart: always
        ports:
            - 8080:80
    maccms-db:
        image: mariadb:10.3
        container_name: maccms-db
        restart: always
        environment:
            - MARIADB_ROOT_PASSWORD=maccms_db_password
